export type LegacyRegressionGroup = {
  name: string;
  cases: Record<string, string[]>;
};

export const legacyRegressionGroups: LegacyRegressionGroup[] = [
  {
    name: 'consonant digraph ng',
    cases: {
      anjing: ['an', 'jing'],
      kucing: ['ku', 'cing'],
      kambing: ['kam', 'bing'],
      aliang: ['ali', 'ang'],
      acung: ['a', 'cung'],
      long: ['long'],
      aong: ['a', 'ong'],
      uang: ['u', 'ang'],
      wong: ['wong'],
      gombrang: ['gom', 'brang'],
      kecombrang: ['kecom', 'brang'],
      gondrong: ['gon', 'drong'],
      begandering: ['begande', 'ring'],
      haramonting: ['haramon', 'ting'],
      berjerangkang: ['berjerang', 'kang'],
      terhembalang: ['terhemba', 'lang'],
      tergantung: ['tergan', 'tung'],
      terbayang: ['terba', 'yang'],
      terbang: ['ter', 'bang'],
      bayang: ['ba', 'yang'],
      gambreng: ['gam', 'breng'],
      setormking: ['setorm', 'king'],
      sipongang: ['sipo', 'ngang'],
      semprong: ['sem', 'prong'],
      sinambung: ['sinam', 'bung'],
      segamblang: ['segam', 'blang'],
      gamblang: ['gam', 'blang'],
      sling: ['sling'],
      blang: ['blang'],
      nyang: ['nyang'],
      plong: ['plong'],
      ngung: ['ngung'],
      wrang: ['wrang'],
      hyang: ['hyang'],
      meong: ['me', 'ong'],
      keong: ['ke', 'ong'],
      taung: ['ta', 'ung'],
      piong: ['pi', 'ong'],
    },
  },
  {
    name: 'consonant digraph kh',
    cases: {
      bakh: ['bakh'],
      syekh: ['syekh'],
      muarikh: ['mua', 'rikh'],
      mansukh: ['man', 'sukh'],
      tarikh: ['ta', 'rikh'],
    },
  },
  {
    name: 'consonant digraph sy',
    cases: {
      arasy: ['a', 'rasy'],
      bihausy: ['biha', 'usy'],
      quraisy: ['qura', 'isy'],
      tarkasy: ['tar', 'kasy'],
    },
  },
  {
    name: 'CCC endings',
    cases: {
      korps: ['korps'],
      hertz: ['hertz'],
      kilohertz: ['kilo', 'hertz'],
      megahertz: ['mega', 'hertz'],
      gigahertz: ['giga', 'hertz'],
      terahertz: ['tera', 'hertz'],
      semiarts: ['semi', 'arts'],
    },
  },
  {
    name: 'CC endings',
    cases: {
      ambiens: ['ambi', 'ens'],
      kompleks: ['kom', 'pleks'],
      pusdikart: ['pusdi', 'kart'],
      oligark: ['oli', 'gark'],
      trans: ['trans'],
      uniform: ['uni', 'form'],
      yoghurt: ['yog', 'hurt'],
    },
  },
  {
    name: 'VC endings',
    cases: {
      'berangan-angan': ['berangan-a', 'ngan'],
      'bercakap-cakap': ['bercakap-ca', 'kap'],
      angan: ['a', 'ngan'],
      anyam: ['a', 'nyam'],
      bajingan: ['baji', 'ngan'],
      komplek: ['kom', 'plek'],
      imlek: ['im', 'lek'],
      imsak: ['im', 'sak'],
      liat: ['li', 'at'],
      lihat: ['li', 'hat'],
      elektabilitas: ['elektabili', 'tas'],
      taun: ['ta', 'un'],
      poin: ['po', 'in'],
      tren: ['tren'],
      bawah: ['ba', 'wah'],
      gram: ['gram'],
      aerogram: ['aero', 'gram'],
      ambigram: ['ambi', 'gram'],
    },
  },
  {
    name: 'CV endings',
    cases: {
      'berkata-kata': ['berkata-ka', 'ta'],
      kena: ['ke', 'na'],
      dungu: ['du', 'ngu'],
      alegro: ['aleg', 'ro'],
      tungro: ['tung', 'ro'],
      mengajangi: ['mengaja', 'ngi'],
      bernyanyi: ['bernya', 'nyi'],
      bunga: ['bu', 'nga'],
      adipuisi: ['adipui', 'si'],
      puisi: ['pui', 'si'],
      sekenyangnya: ['sekenyang', 'nya'],
      wushu: ['wu', 'shu'],
      wudhu: ['wu', 'dhu'],
      ridha: ['ri', 'dha'],
      ridho: ['ri', 'dho'],
      iduladha: ['idulad', 'ha'],
      kungfu: ['kung', 'fu'],
      ungu: ['u', 'ngu'],
      koreksi: ['korek', 'si'],
      mengoreksi: ['mengorek', 'si'],
      menyayangi: ['menyaya', 'ngi'],
    },
  },
  {
    name: 'VVV endings',
    cases: {
      sesuai: ['sesu', 'ai'],
      labeau: ['labe', 'au'],
    },
  },
  {
    name: 'VV endings',
    cases: {
      tergapai: ['terga', 'pai'],
      anortopsia: ['anortopsi', 'a'],
      sukaria: ['sukari', 'a'],
      ria: ['ri', 'a'],
      ceria: ['ceri', 'a'],
      euforia: ['eufori', 'a'],
      semua: ['semu', 'a'],
      papua: ['papu', 'a'],
      tetua: ['tetu', 'a'],
      tertua: ['tertu', 'a'],
      alinea: ['aline', 'a'],
      korea: ['kore', 'a'],
      tionhoa: ['tionho', 'a'],
      protozoa: ['protozo', 'a'],
      doa: ['do', 'a'],
      terangkai: ['terang', 'kai'],
      merangkai: ['merang', 'kai'],
      ternodai: ['ternoda', 'i'],
      menodai: ['menoda', 'i'],
      mewarnai: ['mewarna', 'i'],
      menilai: ['meni', 'lai'],
      menua: ['menu', 'a'],
      menuai: ['menu', 'ai'],
      mengusai: ['mengu', 'sai'],
      menguasai: ['menguasa', 'i'],
      mempercayai: ['mempercaya', 'i'],
      memperduai: ['memperdua', 'i'],
      berdamai: ['berda', 'mai'],
      yahrai: ['yah', 'rai'],
      survei: ['sur', 'vei'],
      suplai: ['sup', 'lai'],
      menyuplai: ['menyup', 'lai'],
      menyeringai: ['menyeri', 'ngai'],
      menyiksai: ['menyiksa', 'i'],
      menyerupai: ['menyerupa', 'i'],
      menyangai: ['menya', 'ngai'],
      memolai: ['memola', 'i'],
      memulai: ['memu', 'lai'],
      menggeragai: ['menggera', 'gai'],
      fengsui: ['feng', 'sui'],
      mencandui: ['mencandu', 'i'],
      menemui: ['menemu', 'i'],
      mengakui: ['mengaku', 'i'],
      relikui: ['reli', 'kui'],
      berui: ['be', 'rui'],
      uncui: ['un', 'cui'],
      mei: ['mei'],
      mekwei: ['mek', 'wei'],
      menggei: ['meng', 'gei'],
      menggwei: ['meng', 'gwei'],
      menyurvei: ['menyur', 'vei'],
      jersei: ['jer', 'sei'],
      kriau: ['kri', 'au'],
      cepiau: ['cepi', 'au'],
      ketiau: ['keti', 'au'],
      kwetiau: ['kweti', 'au'],
      panggau: ['pang', 'gau'],
      serantau: ['seran', 'tau'],
      kau: ['kau'],
      bau: ['ba', 'u'],
      langau: ['la', 'ngau'],
      aliliu: ['alili', 'u'],
      angciu: ['angci', 'u'],
      baliu: ['bali', 'u'],
      baniu: ['bani', 'u'],
      interpiu: ['interpi', 'u'],
      interviu: ['intervi', 'u'],
      kampuriu: ['kampuri', 'u'],
      penginterviu: ['pengintervi', 'u'],
      reviu: ['revi', 'u'],
      seliu: ['seli', 'u'],
      menginterviu: ['mengintervi', 'u'],
      mensiu: ['mensi', 'u'],
      mesiu: ['mesi', 'u'],
      rahambuu: ['raham', 'buu'],
      sadeu: ['sa', 'deu'],
      tefeu: ['tefe', 'u'],
      mondou: ['mon', 'dou'],
      alangkitae: ['alangkita', 'e'],
      alawatae: ['alawata', 'e'],
      alingkitae: ['alingkita', 'e'],
      asteraseae: ['asterasea', 'e'],
      bantae: ['banta', 'e'],
      gimnospermae: ['gimnosperma', 'e'],
      honae: ['hona', 'e'],
      lorantaseae: ['lorantasea', 'e'],
      mambae: ['mamba', 'e'],
      manbae: ['manba', 'e'],
      pattae: ['patta', 'e'],
      perquisitae: ['perquisita', 'e'],
      reggae: ['regga', 'e'],
      siperaseae: ['siperasea', 'e'],
      termae: ['terma', 'e'],
      undae: ['unda', 'e'],
      wadilae: ['wadila', 'e'],
    },
  },
];

export const legacyRegressionCases = legacyRegressionGroups.flatMap((group) =>
  Object.entries(group.cases).map(([word, expected]) => ({
    group: group.name,
    word,
    expected,
  })),
);
